version: '2'
services:
  kibana:
    build: dockerfiles/kibana
    ports:
      - "5601:5601"
  kibana3:
    build: dockerfiles/kibana3
    ports:
      - "8080:8080"
  logstash:
    build:
      context: ./logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/patterns:/usr/share/logstash/patterns
  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
  grafana:
    build: dockerfiles/grafana-docker
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
  graphite:
    build: dockerfiles/docker-graphite-statsd
    ports:
      - "80:80"
      - "2003:2003"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - ./data/graphite-statsd/whisper:/opt/graphite/storage/whisper
  smokeping:
    build: dockerfiles/smokeping
    ports:
      - "8000:80"
    volumes:
      - ./data/smokeping/cache:/var/cache/smokeping
      - ./data/smokeping/lib:/var/lib/smokeping
      - ./dockerfiles/smokeping/conf/smokeping/config.d:/etc/smokeping/config.d
