version: '2'
services:
  kibana:
    extends:
      file: common.yml
      service: kibana
    extra_hosts:
      - "elasticsearch:<ip>"
  logstash:
    extends:
      file: common.yml
      service: logstash
    extra_hosts:
      - "elasticsearch:<ip>"
  cadvisor:
    extends:
      file: common.yml
      service: cadvisor
