version: '2'
services:
  kibana:
    extends:
      file: common.yml
      service: kibana
    image: unicell/kibana:latest
    extra_hosts:
      - "elasticsearch:<ip>"
  logstash:
    extends:
      file: common.yml
      service: logstash
    extra_hosts:
      - "elasticsearch:<ip>"
  cadvsor:
    extends:
      file: common.yml
      service: cadvisor
