version: '2'
services:
  elasticsearch:
    extends:
      file: common.yml
      service: elasticsearch
    image: unicell/elasticsearch:latest
  kibana:
    extends:
      file: common.yml
      service: kibana
    image: unicell/kibana:latest
    links:
      - elasticsearch
