version: '2'
services:
  logstash:
    extends:
      file: common.yml
      service: logstash
    image: unicell/logstash:latest
    extra_hosts:
      - "elasticsearch: ${ES_HOST}"
  logspout:
    extends:
      file: common.yml
      service: logspout
    image: unicell/logspout:v3-master
    environment:
      DEBUG: true
    links:
      - logstash
    command: syslog://logstash:5000
  cadvisor:
    extends:
      file: common.yml
      service: cadvisor
